### PR TITLE
Feature/apply certification

### PR DESCRIPTION
**Pull request by pengcc**
update certification page #314

### CODE REVIEW

**Comment by zhaofeng-shu33** [comment]
> update certification page

You need to merge the dev branch first.

**Comment by zhaofeng-shu33** [comment]
@pengcc Do you really need force-push?

**Comment by pengcc** [comment]
> @pengcc Do you really need force-push?

 I think I don't have to force push. I did this following the  wuhan2020.github.io/docs/zh-cn/dev/contributing.md, 7:  git push -f origin my-fix-branch:my-fix-branch. If this is not mandatory. Maybe the contributing.md should be updated accordingly.

**Comment by zhaofeng-shu33** [comment]
> > @pengcc Do you really need force-push?
> 
> I think I don't have to force push. I did this following the wuhan2020.github.io/docs/zh-cn/dev/contributing.md, 7: git push -f origin my-fix-branch:my-fix-branch. If this is not mandatory. Maybe the contributing.md should be updated accordingly.

I think we should update the doc about the use of `-f` @lovepoem . I think force push is a bad idea.

**Comment by pengcc** [comment]
> > > @pengcc Do you really need force-push?
> > 
> > 
> > I think I don't have to force push. I did this following the wuhan2020.github.io/docs/zh-cn/dev/contributing.md, 7: git push -f origin my-fix-branch:my-fix-branch. If this is not mandatory. Maybe the contributing.md should be updated accordingly.
> 
> I think we should update the doc about the use of `-f` @lovepoem . I think force push is a bad idea.

I just tried wihout -f
❯ git push origin feature/apply-certification:feature/apply-certification
To github.com:pengcc/wuhan2020.github.io-1.git
 ! [rejected]        feature/apply-certification -> feature/apply-certification (non-fast-forward)
error: failed to push some refs to 'git@github.com:pengcc/wuhan2020.github.io-1.git'

It seems that force-push is mandatory to push changes from the forked repo to the origin. 
Maybe there is a better soluton without force push. See PR #334

**Comment by zhaofeng-shu33** [comment]
You should merge the upstream dev branch.  Thus force push is not necessary.

**Comment by zhaofeng-shu33** [comment]
New code introduces Issue #335 .

**Review by zhaofeng-shu33 — COMMENTED** [review]
LGTM

**Review by lovepoem — APPROVED** [review]
LGTM

**Pull request merged**
