### PR TITLE
update i18n/it-it.js

### LINKED ISSUE #263: Wrong titles/links in the italian version of the documentation section’s side menu
Some parts of the italian version of the documentation section’s side menu contain wrong titles and links, please correct as follows:

- Panoramica
-- Di cosa si occupa Wuahan2020?
-- FAQ
- Guide per gli utenti
-- Guida alla piattaforma di prevenzione epidemica COVID-19
- Guide per gli sviluppatori
-- Quickstart
-- Flusso di lavoro del team (Cinese)
-- Guida alla raccolta dati
-- Guida all’iscrizione alla mailing list (Cinese)
-- Diagramma dell'architettura (Inglese)
-- Guida alla partecipazione (Inglese)
-- Gestione del repository su GitHub (Inglese)

**Information guide wrong link and title:**
`<a href="/en-us/docs/dev/information-guide.html" target="_self">Guida alla raccolta dei dati (Inglese)</a>`
**should be:**
`<a href="/it-it/docs/dev/information-guide.html" target="_self">Guida alla raccolta dati</a>`

@GindaChen, these bugs are those I briefly informed you about, please have a look.

Thanks!

### PR DESCRIPTION
**Pull request by jeremy0519**
closes #263

### CODE REVIEW

**Comment by jeremy0519** [comment]
#263

**Comment by chenrui333** [comment]
I think you should create a new branch for every change 😅

**Review by chenrui333 — APPROVED** [review]
👍

**Comment by jeremy0519** [comment]
oh, I forgot it.

**Comment by jeremy0519** [comment]
Thanks for your remind.

**Comment by chenrui333** [comment]
np, change looks good though.

**Comment by jeremy0519** [comment]
@lovepoem

**Comment by lovepoem** [comment]
LGTM

**Pull request merged**
