### PR TITLE
Added the Chinese version of how to join Wuhan2020

### PR DESCRIPTION
**Pull request by iLtc**
The English version will be published soon.

### CODE REVIEW

**Comment by lovepoem** [comment]
Please add some config in community.js

**Comment by iLtc** [comment]
@lovepoem I have added the article to the community page.

Notice that the articles on the community page are displayed horizontally. If there are too many articles in the future, it will be difficult for users to read the list.

**Review by GindaChen — APPROVED** [review]
LGTM. Would you like to add another issue to ask for the translation for this page?

**Comment by iLtc** [comment]
@GindaChen The English version is ready. I just need to do some Ctrl+C and Ctrl+V work.

Should we raise an issue for other languages? I am not sure if we need to translate every article to every language?

**Comment by GindaChen** [comment]
Just raise an epic issue about trans requst for all possible lang.

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
