### PR TITLE
Translation docs ptbr

### PR DESCRIPTION
**Pull request by kevenleone**
According to #52 Issue that I created, I've made the translation for docs(REDMEs) and the website in pt-br (Brazilian Portuguese)

Hope this can help people around the world 🇧🇷

### CODE REVIEW

**Comment by lovepoem** [comment]
Awesome pr ！

**Comment by kevenleone** [comment]
> Awesome pr ！

Thanks 😄

**Review by chenrui333 — APPROVED** [review]
💯

**Comment by chenrui333** [comment]
I will let @GindaChen review on this as well :)

**Comment by GindaChen** [comment]
This is a great PR ! Thank you !!! I recommend we clean up some of the files before we commit.

**Comment by GindaChen** [comment]
@kevenleone You can add in the `.gitignore` the static pages of the language. The Github Action robot will generate those when built.

**Pull request merged**
