### PR TITLE
[WIP] Add valine plugin

### PR DESCRIPTION
**Pull request by jeremy0519**
好像评论显示在了copyright下面

### CODE REVIEW

**Comment by jeremy0519** [comment]
报错没有

**Comment by lovepoem** [comment]
截图展示下效果

**Comment by jeremy0519** [comment]
valine

**Comment by jeremy0519** [comment]
可以把placeholder改掉

**Comment by jeremy0519** [comment]
valine不需要github账号

**Comment by zhaofeng-shu33** [comment]
This should be integrated with React.  Thus the comment blocks can be put above the footer.

**Comment by jeremy0519** [comment]
> Valine has been released to npm and can be installed directly by command.

See [valine's official website](https://valine.js.org/en/quickstart.html#npm) for more details.

**Comment by jeremy0519** [comment]
@zhaofeng-shu33 Can you fix this issue?

**Comment by jeremy0519** [comment]
I don't think the code should be put at `template.ejs` because we don't need the comment box on the home page.

**Comment by zhaofeng-shu33** [comment]
Maybe @pengcc is better than me.

**Comment by jeremy0519** [comment]
@pengcc Can you fix the position problem?

**Comment by pengcc** [comment]
@jeremy0519 
hi, what's the current requirement? which position problem should be fixed? I didn't follow up this topic. By the way, the screenshot is blurred. If possible provide a clear picture with instruction. What is the current issue and what is expected.

**Comment by pengcc** [comment]
I agree with @zhaofeng-shu33. There is no necessity to add the code to the template.ejs. I am not familiar with this topic yet. But in general, there is a better way to implement a new feature.

**Comment by jeremy0519** [comment]
> @jeremy0519
> hi, what's the current requirement? which position problem should be fixed? I didn't follow up this topic. By the way, the screenshot is blurred. If possible provide a clear picture with instruction. What is the current issue and what is expected.

@pengcc 
Hi, as there is an error when we use gitalk comment, I decide to use valine comment instead. It loads faster than gitalk and has no backend. It uses [leancloud](https://leancloud.app) to store all the comments.
Current issue:
I don't know where to put the code. I put it in template.ejs and it displays under the footer.
What is expected:
It should display under each documention, blog, community...

**Comment by pengcc** [comment]
Hi, I just tried valine and react-valine, it seems a bit complicated to use it. I got an error ` ReferenceError: Storage is not defined `while compiling when I import the valine into the component footer. It could need more time to debug or read the documentation to understand how to use it properly. I can't find too much time to implement this feature right now. I have to focus on the stuff 'refactoring' which I started. In my view, refactoring the current code is much more important.

Maybe you can find someone else, who has time and is familiar with valine to implement it right now.  Otherwise, I could be free earliest after next weekend.

I would suggest moving the code of this feature into the Footer component. But I didn't get it successfully.

**Comment by lovepoem** [comment]
Can a  administrator  delete one comment ？
How to set some administrators ?

**Comment by jeremy0519** [comment]
> Can a administrator delete one comment ？
> How to set some administrators ?

Yes. You can register a leancloud account and I can invite you to collaborate on the leancloud app. Then you will be able to edit or delete comments.

**Comment by jeremy0519** [comment]
Make sure to register at the international site (not china site)
Register link: https://console.leancloud.app/login.html#/signup

**Comment by jeremy0519** [comment]
​@lovepoem 显示位置不正确是因为我放在了template.ejs下面，主要还是报错问题

**Comment by jeremy0519** [comment]
Gitalk is already added.

**Pull request closed without merging**
