### PR TITLE
Improvement: upgrade react

### PR DESCRIPTION
**Pull request by pengcc**
- remove react reference from package.json avoiding two copies
  - docsite install the react references already
  - using the latest local react libraries instead of old CDN
  - update babelrc plugins settings to enable async

### CODE REVIEW

**Comment by pengcc** [comment]
not merge yet, TBD

**Comment by zhaofeng-shu33** [comment]
I do not suggest put react production code within this repo.

**Comment by pengcc** [comment]
> I do not suggest put react production code within this repo.

what's your suggestion? you prefer to CDN or you want to use the development code? due to the docsite limit currently no way to dynamic load development or production. The docsite compiles the template.ejs to generate HTML. I will talk to the author of doctite about this issue. Try to find out if there is a way to customize the template.ejs.

**Comment by zhaofeng-shu33** [comment]
> > I do not suggest put react production code within this repo.
> 
> what's your suggestion? you prefer to CDN or you want to use the development code? due to the docsite limit currently no way to dynamic load development or production. The docsite compiles the template.ejs to generate HTML. I will talk to the author of doctite about this issue. Try to find out if there is a way to customize the template.ejs.

I think webpack has already packed react in js code. No need to include it using html script tag.

**Comment by pengcc** [comment]
> > > I do not suggest put react production code within this repo.
> > 
> > 
> > what's your suggestion? you prefer to CDN or you want to use the development code? due to the docsite limit currently no way to dynamic load development or production. The docsite compiles the template.ejs to generate HTML. I will talk to the author of doctite about this issue. Try to find out if there is a way to customize the template.ejs.
> 
> I think webpack has already packed react in js code. No need to include it using html script tag.

I see. Webpack can work in the way that you pointed. But webpack currently doesn't work in this way due to the setting: 
`externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
  }`
the reason for this, maybe this could be helpful https://github.com/youngwind/blog/issues/65

**Comment by pengcc** [comment]
Is it possible to let DeepScan ignore the react lib file? if not, I need to think about using CDN instead or find a better lib without such stupid errors? Alle the current errors are caused by lib/react-dom.development.js, which we will not touch and this file will only be used in the development environment.

Please take a look.

**Comment by zhaofeng-shu33** [comment]
> > > > I do not suggest put react production code within this repo.
> > > 
> > > 
> > > what's your suggestion? you prefer to CDN or you want to use the development code? due to the docsite limit currently no way to dynamic load development or production. The docsite compiles the template.ejs to generate HTML. I will talk to the author of doctite about this issue. Try to find out if there is a way to customize the template.ejs.
> > 
> > 
> > I think webpack has already packed react in js code. No need to include it using html script tag.
> 
> I see. Webpack can work in the way that you pointed. But webpack currently doesn't work in this way due to the setting:
> `externals: { react: 'React', 'react-dom': 'ReactDOM', }`
> the reason for this, maybe this could be helpful [youngwind/blog#65](https://github.com/youngwind/blog/issues/65)

Ok, this external reference has some advantages in reducing the single JavaScript bundle size. I think the version of external react should be consistent with `npm_modules/react`. I wonder why webpack has some internal support for such purpose instead of using external strategy.

**Comment by zhaofeng-shu33** [comment]
> Is it possible to let DeepScan ignore the react lib file? if not, I need to think about using CDN instead or find a better lib without such stupid errors? Alle the current errors are caused by lib/react-dom.development.js, which we will not touch and this file will only be used in the development environment.
> 
> Please take a look.

Since webpack config file is actually a JavaScript file and can be modified on the fly. I suggest in development mode using webpack to inject React development code; In Release mode, using `<script src=""/>` to handle the big size problem.

**Comment by pengcc** [comment]
> > > > > I do not suggest put react production code within this repo.
> > > > 
> > > > 
> > > > what's your suggestion? you prefer to CDN or you want to use the development code? due to the docsite limit currently no way to dynamic load development or production. The docsite compiles the template.ejs to generate HTML. I will talk to the author of doctite about this issue. Try to find out if there is a way to customize the template.ejs.
> > > 
> > > 
> > > I think webpack has already packed react in js code. No need to include it using html script tag.
> > 
> > 
> > I see. Webpack can work in the way that you pointed. But webpack currently doesn't work in this way due to the setting:
> > `externals: { react: 'React', 'react-dom': 'ReactDOM', }`
> > the reason for this, maybe this could be helpful [youngwind/blog#65](https://github.com/youngwind/blog/issues/65)
> 
> Ok, this external reference has some advantages in reducing the single JavaScript bundle size. I think the version of external react should be consistent with `npm_modules/react`. I wonder why webpack has some internal support for such purpose instead of using external strategy.

Indeed, the version of react lib should be consistent with the version of the reference react package in node_modules. And current they are consistent. Firstly to check the version just open the target file (lib) and the reference package, it's easy to find the version, both are 16.13.0. Secondly, it's about the Semantic Versioning. In short, 
```
So if you see ~1.0.2 it means to install version 1.0.2 or the latest patch version such as 1.0.4. If you see ^1.0.2 it means to install version 1.0.2 or the latest minor or patch version such as 1.1.0.
```
In the current project, in docsite/package.json seeing "react": "^16.5.2", means the latest version 16.13.0 will be installed. same to the react-dom and the others.
More information can be found easily found by google maybe.

**Comment by pengcc** [comment]
> > Is it possible to let DeepScan ignore the react lib file? if not, I need to think about using CDN instead or find a better lib without such stupid errors? Alle the current errors are caused by lib/react-dom.development.js, which we will not touch and this file will only be used in the development environment.
> > Please take a look.
> 
> Since webpack config file is actually a JavaScript file and can be modified on the fly. I suggest in development mode using webpack to inject React development code; In Release mode, using `<script src=""/>` to handle the big size problem.

Sure, we can alter the webpack config. But can do doesn't have to or need to do. And obviously, we can even upgrade webpack to v4 to get more abilities. But I would say, maybe in the next stage. I would like to just upgrade react for now. If everything works well, we can think about the next improvement.

**Comment by zhaofeng-shu33** [comment]
Maybe adding the react version information to `dev-dependencies` in `package.json`?

**Review by lovepoem — APPROVED** [review]

**Review by lovepoem — APPROVED** [review]

**Pull request merged**
