### PR TITLE
italian translation: update portal contents

### PR DESCRIPTION
**Pull request by Atena1118**
I refined the contents of some pages —— home , docs, contributors, blog —— of our portal (Italian Version)
我优化了咱们门户网的意大利语版的几个页面的内容，这几个页面分别是：主页、文档、贡献者、博客。
添加了如下几个文件：
BLOG博客.md
DOCUMENTAZIONE文档.md
HOME主页.md
SOSTENITORI贡献者.md

### CODE REVIEW

**Review by chenrui333 — CHANGES_REQUESTED** [review]
位置不太对。我等会修改一下。

**Comment by Atena1118** [comment]
> 位置不太对。我等会修改一下。

好的，谢谢！辛苦技术员您了！ 我这边是小白一个，就是因为不知道该放哪里，我就干脆放在仓库的根目录下的。。。请见谅！

**Comment by chenrui333** [comment]
没事，随意放。也辛苦你们翻译校对了。

**Comment by chenrui333** [comment]
@Atena1118 @GindaChen updated, 你们再看看。

**Review by chenrui333 — APPROVED** [review]
moved all the files to corresponding ones.

**Comment by GindaChen** [comment]
`docs/it-it/developers/developers_dev.md` markdown  chart seems werid. Would you like to take a look?

**Comment by chenrui333** [comment]
@Atena1118 你需要运行一下下面的命令来 update 一下你的分支。

```
git checkout dev # ensure branch location
git remote add wuhan2020 git@github.com:wuhan2020/wuhan2020.github.io.git 
git pull wuhan2020 dev # (wuhan2020 dev -> local dev)
git push origin dev # (updated 你的 fork)
```

**Comment by chenrui333** [comment]
> `docs/it-it/developers/developers_dev.md` markdown chart seems werid. Would you like to take a look?

not quite sure if I understand correct, i am mostly trying to migrate the content from one md to the exiting one.

**Comment by iLtc** [comment]
@GindaChen I compared it with the Chinese version, and it looks similar. Which part do you think is weird?

it-it: https://raw.githubusercontent.com/wuhan2020/wuhan2020.github.io/d199599a31e06953a66e7444b40758fd4c970110/docs/it-it/developers/developers_dev.md

zh-cn: https://raw.githubusercontent.com/wuhan2020/wuhan2020.github.io/dev/docs/zh-cn/developers/developers_dev.md

**Comment by chenrui333** [comment]
@GindaChen fixed the markdown syntax :)

**Review by GindaChen — APPROVED** [review]

**Pull request merged**
