### PR TITLE
[WIP] Update hackathon part in en-us.js

### PR DESCRIPTION
**Pull request by jeremy0519**
add speaker list

### CODE REVIEW

**Comment by jeremy0519** [comment]
#315

**Comment by jeremy0519** [comment]
@zhaofeng-shu33

**Comment by zhaofeng-shu33** [comment]
Why the pr is merged with the title "[WIP]..."?

**Comment by jeremy0519** [comment]
Oh, it shouldn't be merged.

**Comment by jeremy0519** [comment]
I'll revert this and raise a new pr.

**Comment by jeremy0519** [comment]
There are still 4 sections: subject, activity, holder, application.

**Pull request merged**
