### PR TITLE
Revert "[WIP] Update hackathon part in en-us.js (#327)"

### PR DESCRIPTION
**Pull request by jeremy0519**
This reverts commit 3f8d9e6abef69513ff4c5e2f45346f8cf110341e.

### CODE REVIEW

**Comment by lovepoem** [comment]
Why do you revert this ?

**Comment by jeremy0519** [comment]
It's ok. @zhaofeng-shu33 have merged a new pr.

**Comment by zhaofeng-shu33** [comment]
The pr should be closed?

**Comment by jeremy0519** [comment]
At least I think so.

**Pull request merged**
