### PR TITLE
Updated Image Actions Configuration

### LINKED ISSUE #231: Using `image-actions.yml` for configuration is deprecated
Reference run, https://github.com/wuhan2020/wuhan2020.github.io/actions/runs/39537969

image

### PR DESCRIPTION
**Pull request by iLtc**
Updated Image Actions configuration file base on https://github.com/calibreapp/image-actions.

Fix #231

### CODE REVIEW

**Comment by iLtc** [comment]
I am not sure about this error:

image

**Comment by chenrui333** [comment]
Very nice!!

**Comment by chenrui333** [comment]
> I am not sure about this error:


that is related to https://github.com/calibreapp/image-actions/issues/31

**Comment by chenrui333** [comment]
@iLtc I will create another issue for this thing.

**Pull request merged**
