### PR TITLE
update project.js, fix #192

### LINKED ISSUE #192: 【翻译 中文---意大利文】项目列表页翻译
## 描述你需要修改或新增的文档
将中文文档 https://community.wuhan2020.org.cn/zh-cn/project/index.html
翻译成英文 https://community.wuhan2020.org.cn/it-it/project/index.html

 源码地址： /site_config/project.js

### PR DESCRIPTION
**Pull request by jeremy0519**
项目列表页意大利文翻译 #192

### CODE REVIEW

**Review by GindaChen — APPROVED** [review]
LGTM!

**Comment by GindaChen** [comment]
@Atena1118 Would love you have a look

**Comment by jeremy0519** [comment]
thanks

**Comment by jeremy0519** [comment]
i use the youdao translation tool, so someone had better check it before merge.

**Pull request merged**
