### PR TITLE
add gitalk in docs module

### PR DESCRIPTION
**Pull request by lovepoem**
add Gitalk
But now when you run ` npm run start`

it occurs

```log

(node:22541) UnhandledPromiseRejectionWarning: SecurityError: localStorage is not available for opaque origins
    at Window.localStorage (/Users/wx/workspace/wuhan2020.github.io/node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
    at new GitalkComponent (/Users/wx/workspace/wuhan2020.github.io/node_modules/gitalk/dist/webpack:/gitalk.jsx:84:34)
    at processChild (/Users/wx/workspace/wuhan2020.github.io/node_modules/react-dom/cjs/react-dom-server.node.development.js:2995:14)
    at resolve (/Users/wx/workspace/wuhan2020.github.io/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/Users/wx/workspace/wuhan2020.github.io/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/Users/wx/workspace/wuhan2020.github.io/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at Object.renderToString (/Users/wx/workspace/wuhan2020.github.io/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at files.forEach.file (/Users/wx/workspace/wuhan2020.github.io/node_modules/docsite/lib/generateJSONFile.js:87:38)
    at Array.forEach (<anonymous>)
    at parse (/Users/wx/workspace/wuhan2020.github.io/node_modules/docsite/lib/generateJSONFile.js:39:11)
(node:22541) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22541) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

### CODE REVIEW

**Comment by jeremy0519** [comment]
I encountered the same problem when using gitalk.

**Comment by jeremy0519** [comment]
So I decided to use valine. But the comment part is under the copyright part.

**Comment by jeremy0519** [comment]
See #470

**Comment by zhaofeng-shu33** [comment]
> Can we really add gittalk?

Yes if it works well

**Comment by zhaofeng-shu33** [comment]
valine is ok if it works

**Comment by jeremy0519** [comment]
There is no error if valine is used, but I'm not sure where to put the code

**Comment by jeremy0519** [comment]
I put the code in `template.ejs`, but the comment box is under the copyright.

**Comment by lovepoem** [comment]
> There is no error if valine is used, but I'm not sure where to put the code

Does valine use github issues to store comments as gitalk ?

**Comment by jeremy0519** [comment]
No. It uses [leancloud](https://leancloud.cn). But there is a github project aimed at managing valine comments.

**Comment by jeremy0519** [comment]
https://github.com/panjunwen/Valine-Admin

**Comment by jeremy0519** [comment]
现在的问题就是评论框显示的位置

**Comment by zhaofeng-shu33** [comment]
I think the position issue can be fixed soon.

**Comment by jeremy0519** [comment]
除了position就没有其他issue了

**Comment by lovepoem** [comment]
> 除了position就没有其他issue了

这个用了leancloud,那如果不想匿名评论，用的什么用户系统？

**Comment by jeremy0519** [comment]
所有用户信息都存储在leancloud里面

> > 除了position就没有其他issue了
> 
> 这个用了leancloud,那如果不想匿名评论，用的什么用户系统？

**Comment by jeremy0519** [comment]
评论界面可以显示昵称和网址，邮箱也可以输入，但是只能在leancloud后台看到，评论界面看不到

**Comment by lovepoem** [comment]
It seems that https://github.com/jsdom/jsdom/issues/2304  have resolved this issue

**Comment by jeremy0519** [comment]
Is it fixed?

**Pull request merged**
