### PR TITLE
hackathon-speaker-list-trans

### PR DESCRIPTION
**Pull request by JCCC001**
hackathon speaker translation from english to chinese.

### CODE REVIEW

**Comment by zhaofeng-shu33** [comment]
what is the purpose of this pr?

**Comment by jeremy0519** [comment]
Did you use some website like google translate? There are some sentences that are not well translated.

**Comment by JCCC001** [comment]
the translation is provided from the introduction file of speakers in shimo

**Comment by zhaofeng-shu33** [comment]
Related to Issue #365.

**Comment by zhaofeng-shu33** [comment]
> Did you use some website like google translate? There are some sentences that are not well translated.

which sentences?

**Comment by zhaofeng-shu33** [comment]
> the translation is provided from the introduction file of speakers in shimo

which shimo file?

**Comment by JCCC001** [comment]
I

> > the translation is provided from the introduction file of speakers in shimo
> 
> which shimo file?

It’s a file used to count all the speakers, which is provided by the other volunteers. And the English introduction of speakers also come from this file.

**Comment by zhaofeng-shu33** [comment]
> I
> 
> > > the translation is provided from the introduction file of speakers in shimo
> > 
> > 
> > which shimo file?
> 
> It’s a file used to count all the speakers, which is provided by the other volunteers. And the English introduction of speakers also come from this file.

Do they have chinese translation already?

**Comment by JCCC001** [comment]
> > I
> > > > the translation is provided from the introduction file of speakers in shimo
> > > 
> > > 
> > > which shimo file?
> > 
> > 
> > It’s a file used to count all the speakers, which is provided by the other volunteers. And the English introduction of speakers also come from this file.
> 
> Do they have chinese translation already?

Yes, it’s what I pushed just now

**Comment by zhaofeng-shu33** [comment]
> > > I
> > > > > the translation is provided from the introduction file of speakers in shimo
> > > > 
> > > > 
> > > > which shimo file?
> > > 
> > > 
> > > It’s a file used to count all the speakers, which is provided by the other volunteers. And the English introduction of speakers also come from this file.
> > 
> > 
> > Do they have chinese translation already?
> 
> Yes, it’s what I pushed just now

Can you provide the original link?

**Review by lovepoem — APPROVED** [review]

**Pull request merged**
