### PR TITLE
[doc][What is Wuhan2020] Revise Japanese Translation - What is Wuhan2020

### PR DESCRIPTION
**Pull request by RRFHOUDEN**
#74

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]
Thanks!

**Review by GindaChen — APPROVED** [review]

**Comment by GindaChen** [comment]
LGTM! Thanks!

**Comment by RRFHOUDEN** [comment]
Thanks.
But, I think I sent PR to incorrect branch.
I sent PR to 'RRFHOUDEN-jp-description-revisino'. Shold I send to 'dev' branch?

**Comment by GindaChen** [comment]
Yeah we should go to `dev` ... Would you like to raise another one?

**Comment by RRFHOUDEN** [comment]
@GindaChen 
Um...
I think I should have sent PR to 'dev', but I sent it to the other branch by mistake didn't I?
If no problem, it's OK.

**Comment by GindaChen** [comment]
I just merged #84. That one's good.

**Comment by RRFHOUDEN** [comment]
Thanks

**Pull request merged**
