### PR TITLE
fix security alert

### PR DESCRIPTION
**Pull request by zhaofeng-shu33**

### CODE REVIEW

**Comment by lovepoem** [comment]
有些不兼容的地方，上次升级后本地报错

**Comment by zhaofeng-shu33** [comment]
> 有些不兼容的地方，上次升级后本地报错

I have tested it locally. The CI also passed. Can you test it locally?

**Comment by lovepoem** [comment]
> > 有些不兼容的地方，上次升级后本地报错
> 
> I have tested it locally. The CI also passed. Can you test it locally?

本地 docsite start 启动不了

**Comment by lovepoem** [comment]
https://github.com/wuhan2020/wuhan2020.github.io/pull/206
曾经合并又revert了

**Comment by lovepoem** [comment]
需要本地测试docsit start后本地是不是报错

**Comment by zhaofeng-shu33** [comment]
No error when using `docsite` to start dev-server

**Review by lovepoem — APPROVED** [review]

**Pull request merged**
