### PR TITLE
[Language] Add French Support in the page

### LINKED ISSUE #120: [Language] Create French Language support
## 描述功能要求

Create the language support for French

### PR DESCRIPTION
**Pull request by GindaChen**
Fix #120

Be careful when merging this branch - people might add docs in the time being.

Question: I did this manually. Am I suppose to do this manually?

### CODE REVIEW

**Comment by GindaChen** [comment]
All list to be translated (in priority)

- [ ] `docs/fr-fr/overview/what-is-wuhan2020.md`
- [ ] `blog/fr-fr/wuhan2020-official-announcement.md`
- [ ] `docs/fr-fr/dev/quickstart.md`,
- [ ] `docs/fr-fr/overview/faq.md`, 
- [ ] `docs/fr-fr/dev/information-guide.md`,
- [ ] `docs/fr-fr/overview`
- [ ] `docs/fr-fr/dev/dev-env-setup.md`,
- [ ] `docs/fr-fr/dev/contributing.md` 
- [ ] `docs/fr-fr/developers/developers_dev.md`

**Comment by lovepoem** [comment]
页面颜色不太对套先revert了

**Comment by GindaChen** [comment]
OK. 你merge之后@我就好 法语那边已经有几个doc出来了

**Comment by lovepoem** [comment]
又回滚了，等@iLtc看看

**Pull request merged**
