### PR TITLE
Create a simple script to list all the docs

### PR DESCRIPTION
**Pull request by GindaChen**
Just list all the existing blogs/docs in one language directory.

### CODE REVIEW

**Comment by shawnpanda** [comment]
May be helpful to add the command and some examples in the docs so that people know how and when to use the script? I am not familiar with the repo and am not sure when people should use this.

**Review by CNYoki — APPROVED** [review]

**Comment by iLtc** [comment]
I had a similar script for the sitemap, but yours is better!

**Comment by chenrui333** [comment]
> May be helpful to add the command and some examples in the docs so that people know how and when to use the script? I am not familiar with the repo and am not sure when people should use this.

+1

**Comment by GindaChen** [comment]
May pick up this later

**Comment by GindaChen** [comment]
Add changes. Let's iterate on this.

**Pull request merged**
